(()=>{'use strict';
const root=document.getElementById('reviewClient');if(!root)return;
const cfg=window.SUPABASE_CONFIG||{},api=window.IRReviews;let token=api.tokenFrom(location.href),loadVersion=0;
async function rpc(name,args){if(!cfg.url||!cfg.anonKey)throw new Error('CONFIGURACAO');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(cfg.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:cfg.anonKey,'Content-Type':'application/json'},body:JSON.stringify(args),signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||'ERRO');return body;}finally{clearTimeout(timeout);}}
function done(){root.innerHTML='<div class="review-confirmation" role="status"><span class="review-confirmation__mark" aria-hidden="true">✓</span><h2>Obrigada pela avaliação!</h2><p>Sua resposta foi registrada e será recebida pelo Espaço I.R.</p></div>';}
function entry(error=''){root.innerHTML='<h2>Avalie seu atendimento</h2><p>Após o serviço, abra o link de avaliação enviado pelo Espaço I.R. Se você já recebeu, cole o link abaixo.</p><form id="reviewLinkForm"><label for="reviewLinkInput">Link recebido</label><input id="reviewLinkInput" type="text" required placeholder="Cole seu link de avaliação" autocomplete="off"><button class="review-primary" type="submit">Abrir avaliação</button><p id="reviewLinkError" class="review-error" role="alert">'+api.esc(error)+'</p></form>';root.querySelector('#reviewLinkForm').onsubmit=e=>{e.preventDefault();const next=api.tokenFrom(root.querySelector('#reviewLinkInput').value);if(!next){root.querySelector('#reviewLinkError').textContent='Cole o link de avaliação recebido do Espaço I.R.';return;}token=next;history.replaceState(null,'','#avaliacoes?convite='+token);load();};}
async function load(){const version=++loadVersion;root.innerHTML='<p role="status">Carregando seu atendimento…</p>';try{const context=await rpc('get_service_review_context',{p_token:token});if(version!==loadVersion)return;if(context.submitted){done();return;}const professional=context.professional==='raquel'?'Raquel':context.professional==='iarytsa'?'Iarytsa':'Espaço I.R';const date=new Date(context.date).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'});root.innerHTML='<h2>Como foi seu atendimento?</h2><div class="review-service"><strong>'+api.esc(context.service)+'</strong><span>'+api.esc(professional)+' · '+api.esc(date)+'</span></div><form id="reviewForm"><fieldset class="review-stars"><legend>Sua nota</legend><div class="review-star-options">'+[1,2,3,4,5].map(n=>'<label><input type="radio" name="rating" value="'+n+'" required aria-label="'+n+(n===1?' estrela':' estrelas')+'"><span aria-hidden="true">★</span></label>').join('')+'</div><p id="reviewRatingLabel" class="review-rating-label" aria-live="polite">Selecione de 1 a 5 estrelas</p></fieldset><label for="reviewComment">Comentário <span>(opcional)</span></label><textarea id="reviewComment" maxlength="1000" rows="5" placeholder="Conte como foi sua experiência"></textarea><p class="review-privacy">Sua avaliação será recebida por Raquel e Iarytsa no painel do Espaço I.R.</p><label class="review-public-consent"><input id="reviewPublicConsent" type="checkbox"><span>Autorizo a exibição da minha nota e do meu comentário na aba O Espaço, sem mostrar meu nome.</span></label><button id="reviewSend" class="review-primary" type="submit">Enviar avaliação</button><p id="reviewFormError" class="review-error" role="alert"></p></form>';
const form=root.querySelector('#reviewForm');form.onchange=()=>{const rating=Number(form.querySelector('[name="rating"]:checked')?.value||0);form.querySelectorAll('.review-star-options label').forEach((label,i)=>label.classList.toggle('filled',i<rating));root.querySelector('#reviewRatingLabel').textContent=rating+' de 5 — '+['','Muito insatisfeita','Insatisfeita','Regular','Satisfeita','Muito satisfeita'][rating];};
form.onsubmit=async e=>{e.preventDefault();const button=root.querySelector('#reviewSend');if(button.disabled)return;const rating=Number(form.querySelector('[name="rating"]:checked')?.value||0);if(rating<1||rating>5)return;button.disabled=true;button.textContent='Enviando…';const errorBox=root.querySelector('#reviewFormError');errorBox.textContent='';try{const isPublic=root.querySelector('#reviewPublicConsent').checked;await rpc('submit_service_review_with_visibility',{p_token:token,p_rating:rating,p_comment:root.querySelector('#reviewComment').value,p_public_visible:isPublic});done();if(isPublic)window.dispatchEvent(new Event('ir-review-submitted'));}catch(error){if(String(error.message).includes('AVALIACAO_JA_ENVIADA')){done();return;}errorBox.textContent=api.message(error);button.disabled=false;button.textContent='Enviar avaliação';}};}catch(error){if(version===loadVersion)entry(api.message(error));}}
if(token){window.IR_NAV?.openPage('avaliacoes',false);load();}else entry();
})();
