-- Execute inside a transaction and roll back all synthetic users and bookings.
DO $$
DECLARE u1 uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();ua uuid:=gen_random_uuid();s1 uuid:=gen_random_uuid();s2 uuid:=gen_random_uuid();sa uuid:=gen_random_uuid();v_id uuid;service uuid;result jsonb;rev timestamptz;d date:=timezone('America/Sao_Paulo',now())::date+160;t time:='03:17';
BEGIN
 INSERT INTO auth.users(id,email,email_confirmed_at,role,aud,created_at,updated_at) VALUES(u1,u1::text||'@example.invalid',now(),'authenticated','authenticated',now(),now()),(u2,u2::text||'@example.invalid',now(),'authenticated','authenticated',now(),now()),(ua,ua::text||'@example.invalid',now(),'authenticated','authenticated',now(),now());
 INSERT INTO auth.sessions(id,user_id,created_at,updated_at) VALUES(s1,u1,now(),now()),(s2,u2,now(),now()),(sa,ua,now(),now());
 INSERT INTO public.admins(user_id) VALUES(ua);
 SELECT id INTO service FROM public.services WHERE active LIMIT 1;
 ASSERT service IS NOT NULL;
 WHILE EXISTS(SELECT 1 FROM public.appointment_availability WHERE available_date=d AND available_time BETWEEN t AND t+interval '2 minutes') OR EXISTS(SELECT 1 FROM public.appointments WHERE appointment_at BETWEEN ((d+t) AT TIME ZONE 'America/Sao_Paulo') AND ((d+t+interval '2 minutes') AT TIME ZONE 'America/Sao_Paulo')) LOOP d:=d-1; END LOOP;
 INSERT INTO public.appointment_availability(available_date,available_time,professional,active) VALUES(d,t,'raquel',true),(d,t+interval '1 minute','raquel',true),(d,t+interval '2 minutes','raquel',true);
 INSERT INTO public.appointments(client_name,client_phone,service_name,appointment_at,professional,status,request_status) VALUES('Fixture conflict','5511000000002','Fixture',(d+t+interval '2 minutes') AT TIME ZONE 'America/Sao_Paulo','raquel','agendado','pendente');
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u1,'role','authenticated','session_id',s1,'user_metadata',jsonb_build_object('admin',true))::text,true);
 PERFORM set_config('role','authenticated',true);
 v_id:=public.create_account_appointment_request('Fixture customer','5511000000001',jsonb_build_array(jsonb_build_object('service_id',service,'quantity',1)),'raquel',d,t,NULL);
 result:=public.get_account_appointment(v_id);rev:=(result->>'updated_at')::timestamptz;
 ASSERT (result->>'id')::uuid=v_id AND (result->>'can_manage')::boolean;
 ASSERT jsonb_array_length(public.get_account_appointments())=1;
 ASSERT (SELECT count(*) FROM public.appointments)=0;
 ASSERT (SELECT count(*) FROM public.clients)=0;
 ASSERT (SELECT count(*) FROM public.expenses)=0;
 ASSERT (SELECT count(*) FROM public.admins)=0;
 ASSERT (SELECT count(*) FROM public.customer_profiles WHERE user_id=u1)=1;
 BEGIN UPDATE public.appointments SET status='cancelado' WHERE id=v_id;ASSERT NOT FOUND; END;
 BEGIN PERFORM 1 FROM customer_private.appointment_owners;RAISE EXCEPTION 'Owner mapping exposed';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN INSERT INTO public.customer_profiles(user_id,full_name,phone) VALUES(u2,'Spoofed','5511000000002');RAISE EXCEPTION 'Other profile writable';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u2,'role','authenticated','session_id',s2)::text,true);
 ASSERT jsonb_array_length(public.get_account_appointments())=0;
 BEGIN PERFORM public.get_account_appointment(v_id);RAISE EXCEPTION 'Other booking exposed';EXCEPTION WHEN insufficient_privilege THEN ASSERT SQLERRM='AGENDAMENTO_INDISPONIVEL';END;
 BEGIN PERFORM public.change_account_appointment(v_id,'cancel',rev);RAISE EXCEPTION 'Other booking editable';EXCEPTION WHEN insufficient_privilege THEN ASSERT SQLERRM='AGENDAMENTO_INDISPONIVEL';END;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u1,'role','authenticated','session_id',s1)::text,true);
 BEGIN PERFORM public.change_account_appointment(v_id,'reschedule',rev,d,(t+interval '2 minutes')::time);RAISE EXCEPTION 'Conflict accepted';EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'HORARIO_INDISPONIVEL' THEN RAISE;END IF;END;
 result:=public.get_account_appointment(v_id);ASSERT (result->>'appointment_at')::timestamptz=((d+t) AT TIME ZONE 'America/Sao_Paulo');
 result:=public.change_account_appointment(v_id,'reschedule',rev,d,(t+interval '1 minute')::time);ASSERT result->>'request_status'='pendente';
 ASSERT (result->>'appointment_at')::timestamptz=((d+t+interval '1 minute') AT TIME ZONE 'America/Sao_Paulo');
 ASSERT EXISTS(SELECT 1 FROM public.get_professional_available_slots(d) WHERE available_date=d AND available_time=t AND professional='raquel');
 BEGIN PERFORM public.change_account_appointment(v_id,'cancel',rev);RAISE EXCEPTION 'Stale revision accepted';EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'AGENDAMENTO_ATUALIZADO' THEN RAISE;END IF;END;
 rev:=(result->>'updated_at')::timestamptz;result:=public.change_account_appointment(v_id,'cancel',rev);ASSERT result->>'status'='cancelado';
 ASSERT EXISTS(SELECT 1 FROM public.get_professional_available_slots(d) WHERE available_date=d AND available_time=(t+interval '1 minute')::time AND professional='raquel');
 result:=public.change_account_appointment(v_id,'cancel',rev);ASSERT result->>'status'='cancelado';
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',ua,'role','authenticated','session_id',sa)::text,true);
 ASSERT (SELECT count(*) FROM public.appointments WHERE id=v_id)=1;
 ASSERT (SELECT private.is_admin());
 PERFORM set_config('role','none',true);
 UPDATE public.appointments SET status='concluido',request_status='confirmado',counted_as_revenue=true,updated_at=clock_timestamp() WHERE id=v_id;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u1,'role','authenticated','session_id',s1)::text,true);PERFORM set_config('role','authenticated',true);
 result:=public.get_account_appointment(v_id);ASSERT NOT (result->>'can_manage')::boolean;
 BEGIN PERFORM public.change_account_appointment(v_id,'cancel',(result->>'updated_at')::timestamptz);RAISE EXCEPTION 'Completed booking editable';EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'AGENDAMENTO_NAO_EDITAVEL' THEN RAISE;END IF;END;
 PERFORM set_config('role','none',true);DELETE FROM auth.sessions WHERE id=s1;
 PERFORM set_config('role','authenticated',true);
 BEGIN PERFORM public.get_account_appointments();RAISE EXCEPTION 'Revoked session accepted';EXCEPTION WHEN insufficient_privilege THEN ASSERT SQLERRM='LOGIN_NECESSARIO';END;
 PERFORM set_config('role','anon',true);
 BEGIN PERFORM public.get_account_appointments();RAISE EXCEPTION 'Anon accepted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 PERFORM set_config('role','none',true);
 ASSERT NOT has_function_privilege('anon','public.change_account_appointment(uuid,text,timestamptz,date,time)','EXECUTE');
END $$;
