(()=>{'use strict';
const cfg=window.SUPABASE_CONFIG||{};
const $=id=>document.getElementById(id);
let db=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>{const [y,m,d]=String(v).split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).replace(/^./,c=>c.toUpperCase())};
async function load(){const {data,error}=await db.from('appointment_availability').select('id,available_date,available_time,active').order('available_date',{ascending:true}).order('available_time',{ascending:true});if(error)throw error;return data||[]}
async function render(){const c=$('content');c.innerHTML='<div class="card"><div class="card-head"><div><h3>Disponibilidade</h3><p>Organize as datas e horários que aparecerão no site da cliente.</p></div></div><form id="availabilityForm" class="toolbar"><input id="avDate" type="date" required><input id="avTime" type="time" required><button class="primary" type="submit">+ Adicionar horário</button></form><p id="avError" class="error"></p><div id="availabilityList">Carregando...</div></div>';$('availabilityForm').onsubmit=add;$('avDate').value=new Date().toISOString().slice(0,10);try{draw(await load())}catch(e){$('availabilityList').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
function draw(rows){const list=$('availabilityList');if(!rows.length){list.innerHTML='<p class="empty">Nenhum horário cadastrado. Adicione a primeira data e horário.</p>';return}const groups={};rows.forEach(r=>(groups[r.available_date]??=[]).push(r));list.innerHTML=Object.entries(groups).map(([date,items])=>'<div class="card" style="margin-top:16px"><div class="card-head"><div><h4>'+esc(fmtDate(date))+'</h4><p>'+items.length+' horário(s) cadastrado(s)</p></div><button class="action danger" data-block-date="'+esc(date)+'">Bloquear dia</button></div>'+items.map(r=>'<div class="service"><div class="service-main"><strong>'+esc(String(r.available_time).slice(0,5))+'</strong><div class="empty">'+(r.active?'Disponível':'Bloqueado')+'</div></div><button class="badge '+(r.active?'':'off')+'" data-toggle-av="'+r.id+'">'+(r.active?'Disponível':'Bloqueado')+'</button><button class="action danger" data-delete-av="'+r.id+'">Excluir</button></div>').join('')+'</div>').join('');document.querySelectorAll('[data-toggle-av]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggleAv));document.querySelectorAll('[data-delete-av]').forEach(b=>b.onclick=()=>remove(b.dataset.deleteAv));document.querySelectorAll('[data-block-date]').forEach(b=>b.onclick=()=>blockDate(b.dataset.blockDate))}
async function add(e){e.preventDefault();$('avError').textContent='';const date=$('avDate').value,time=$('avTime').value;if(!date||!time)return;const {error}=await db.from('appointment_availability').insert({available_date:date,available_time:time+':00',active:true});if(error){$('avError').textContent=error.code==='23505'?'Esse horário já está cadastrado para essa data.':error.message;return}draw(await load())}
async function toggle(id){const rows=await load(),r=rows.find(x=>x.id===id);if(!r)return;const {error}=await db.from('appointment_availability').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else draw(await load())}
async function remove(id){if(!confirm('Excluir este horário?'))return;const {error}=await db.from('appointment_availability').delete().eq('id',id);if(error)alert(error.message);else draw(await load())}
async function blockDate(date){if(!confirm('Bloquear todos os horários de '+fmtDate(date)+'?'))return;const {error}=await db.from('appointment_availability').update({active:false,updated_at:new Date().toISOString()}).eq('available_date',date);if(error)alert(error.message);else draw(await load())}
function setup(){if(!cfg.url||!cfg.anonKey||!window.supabase)return;db=window.supabase.createClient(cfg.url,cfg.anonKey);const nav=document.querySelector('[data-view="availability"]');if(nav)nav.addEventListener('click',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();