(()=>{'use strict';
const cfg=window.SUPABASE_CONFIG||{};
const $=id=>document.getElementById(id);
let db=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>{const [y,m,d]=String(v).split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).replace(/^./,c=>c.toUpperCase())};
async function load(){const rows=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('appointment_availability').select('id,available_date,available_time,active').order('available_date',{ascending:true}).order('available_time',{ascending:true}).order('id',{ascending:true}).range(offset,offset+999);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)return rows;}}
async function render(){const c=$('content');if(!c)return;c.innerHTML='<div class="card"><div class="card-head"><div><h3>Disponibilidade</h3><p>Organize as datas e horários que aparecerão no site da cliente.</p></div></div><div class="av-generator-launch"><button id="openGenerator" type="button" class="primary">Gerar horários de atendimento</button><p>Defina o expediente, a pausa e os dias uma única vez.</p></div><form id="availabilityForm" class="toolbar"><input id="avDate" type="date" required><input id="avTime" type="time" required><button class="primary" type="submit">+ Adicionar horário</button></form><p id="avError" class="error"></p><div id="availabilityList">Carregando...</div></div>';$('availabilityForm').onsubmit=add;$('openGenerator').onclick=openGenerator;$('avDate').value=today();try{draw(await load())}catch(e){$('availabilityList').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
function draw(rows){const list=$('availabilityList');if(!list)return;if(!rows.length){list.innerHTML='<p class="empty">Nenhum horário cadastrado. Adicione a primeira data e horário.</p>';return}const groups={};rows.forEach(r=>(groups[r.available_date]??=[]).push(r));list.innerHTML=Object.entries(groups).map(([date,items])=>'<div class="card" style="margin-top:16px"><div class="card-head"><div><h4>'+esc(fmtDate(date))+'</h4><p>'+items.length+' horário(s) cadastrado(s)</p></div><button class="action danger" type="button" data-block-date="'+esc(date)+'">Bloquear dia</button></div>'+items.map(r=>'<div class="service"><div class="service-main"><strong>'+esc(String(r.available_time).slice(0,5))+'</strong><div class="empty">'+(r.active?'Disponível':'Bloqueado')+'</div></div><button class="badge '+(r.active?'':'off')+'" type="button" data-toggle-av="'+r.id+'">'+(r.active?'Disponível':'Bloqueado')+'</button><button class="action danger" type="button" data-delete-av="'+r.id+'">Excluir</button></div>').join('')+'</div>').join('');document.querySelectorAll('[data-toggle-av]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggleAv));document.querySelectorAll('[data-delete-av]').forEach(b=>b.onclick=()=>remove(b.dataset.deleteAv));document.querySelectorAll('[data-block-date]').forEach(b=>b.onclick=()=>blockDate(b.dataset.blockDate))}
async function add(e){e.preventDefault();$('avError').textContent='';const date=$('avDate').value,time=$('avTime').value;if(!date||!time)return;const {error}=await db.from('appointment_availability').insert({available_date:date,available_time:time+':00',active:true});if(error){$('avError').textContent=error.code==='23505'?'Esse horário já está cadastrado para essa data.':error.message;return}draw(await load())}
async function toggle(id){const rows=await load(),r=rows.find(x=>x.id===id);if(!r)return;const {error}=await db.from('appointment_availability').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else draw(await load())}
async function remove(id){if(!confirm('Excluir este horário?'))return;const {error}=await db.from('appointment_availability').delete().eq('id',id);if(error)alert(error.message);else draw(await load())}
async function blockDate(date){if(!confirm('Bloquear todos os horários de '+fmtDate(date)+'?'))return;const {error}=await db.from('appointment_availability').update({active:false,updated_at:new Date().toISOString()}).eq('available_date',date);if(error)alert(error.message);else draw(await load())}

function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function openGenerator(){
 const dialog=document.createElement('dialog');dialog.className='av-generator';dialog.setAttribute('aria-labelledby','generatorTitle');
 dialog.innerHTML=`<form id="generatorForm"><div class="av-dialog-head"><div><h3 id="generatorTitle">Gerar horários de atendimento</h3><p>Crie vários horários para um dia ou repita a disponibilidade.</p></div><button type="button" class="action" id="generatorClose" aria-label="Fechar">✕</button></div>
 <label>Dia inicial<input id="genDate" type="date" required></label>
 <div class="av-fields"><label>Horário inicial<input id="genStart" type="time" value="08:00" required></label><label>Fim do expediente<input id="genEnd" type="time" value="18:00" required></label><label>Intervalo entre horários<select id="genInterval"><option value="15">15 minutos</option><option value="20">20 minutos</option><option value="30" selected>30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="custom">Personalizado</option></select></label></div>
 <label id="genCustomField" hidden>Intervalo em minutos<input id="genCustom" type="number" min="1" max="720" step="1" value="30"></label>
 <p class="av-hint">São gerados inícios antes do fim do expediente. O intervalo não define a duração do serviço.</p>
 <div class="av-option-card"><label class="av-choice"><input id="genPause" type="checkbox"> Pausa para almoço / intervalo (opcional)</label><div class="av-fields" id="genPauseFields" hidden><label>Início da pausa<input id="genPauseStart" type="time" value="12:00"></label><label>Fim da pausa<input id="genPauseEnd" type="time" value="13:00"></label></div></div>
 <fieldset><legend>Aplicar em quais dias?</legend><label class="av-choice"><input type="radio" name="genMode" value="single" checked> Somente este dia</label><label class="av-choice"><input type="radio" name="genMode" value="repeat"> Repetir disponibilidade</label><div id="genRepeatFields" hidden><label>Repetir até<input id="genUntil" type="date"></label><div class="av-weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((name,i)=>`<label class="av-choice"><input type="checkbox" name="genWeekday" value="${i}" ${i>0&&i<6?'checked':''}>${name}</label>`).join('')}</div></div></fieldset>
 <div class="av-preview"><strong>Prévia dos horários</strong><p id="genSummary" aria-live="polite"></p><div id="genPreview" class="av-chips"></div><p class="av-hint">Horários existentes, bloqueados ou ocupados serão preservados e ignorados na geração.</p></div>
 <p id="genError" class="error" role="alert"></p><div class="av-dialog-actions"><button id="generatorCancel" type="button" class="action">Cancelar</button><button id="generatorSave" class="primary" type="submit">Gerar horários</button></div></form>`;
 document.body.append(dialog);$('genDate').value=$('avDate')?.value||today();$('genUntil').value=$('genDate').value;
 let saving=false;const close=()=>{if(saving)return;dialog.close();dialog.remove();$('openGenerator')?.focus();};
 $('generatorClose').onclick=close;$('generatorCancel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 const options=()=>({date:$('genDate').value,start:$('genStart').value,end:$('genEnd').value,interval:$('genInterval').value==='custom'?$('genCustom').value:$('genInterval').value,pause:$('genPause').checked,pauseStart:$('genPauseStart').value,pauseEnd:$('genPauseEnd').value,repeat:dialog.querySelector('[name="genMode"]:checked').value==='repeat',until:$('genUntil').value,weekdays:[...dialog.querySelectorAll('[name="genWeekday"]:checked')].map(el=>Number(el.value))});
 const preview=()=>{if(saving)return;const o=options();$('genCustomField').hidden=$('genInterval').value!=='custom';$('genPauseFields').hidden=!o.pause;$('genRepeatFields').hidden=!o.repeat;$('genError').textContent='';try{const rows=window.AvailabilityGenerator.generate(o),times=[...new Set(rows.map(r=>r.available_time.slice(0,5)))],days=new Set(rows.map(r=>r.available_date)).size;$('genSummary').textContent=rows.length+' horários em '+days+' dia(s).';$('genPreview').innerHTML=times.map(t=>'<span>'+esc(t)+'</span>').join('');$('generatorSave').disabled=false;}catch(e){$('genError').textContent=e.message;$('genSummary').textContent='Revise a configuração.';$('genPreview').innerHTML='';$('generatorSave').disabled=true;}};
 $('generatorForm').addEventListener('input',preview);$('generatorForm').addEventListener('change',preview);
 $('generatorForm').onsubmit=async e=>{e.preventDefault();if(saving)return;let generated;try{generated=window.AvailabilityGenerator.generate(options());}catch(e){$('genError').textContent=e.message;return;}
 saving=true;const controls=[...dialog.querySelectorAll('input,select,button')];controls.forEach(el=>el.disabled=true);$('generatorSave').textContent='Gerando...';$('genError').textContent='';
 let saved=false;
 try{
 const existing=await load();const occupied=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('appointments').select('id,appointment_at').in('status',['agendado','confirmado','concluido']).gte('appointment_at',generated[0].available_date+'T00:00:00-03:00').lte('appointment_at',generated[generated.length-1].available_date+'T23:59:59-03:00').order('id').range(offset,offset+999);if(error)throw error;for(const a of data||[]){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(a.appointment_at)).reduce((o,p)=>(o[p.type]=p.value,o),{});occupied.push({available_date:parts.year+'-'+parts.month+'-'+parts.day,available_time:parts.hour+':'+parts.minute});}if(!data||data.length<1000)break;}
 const rows=window.AvailabilityGenerator.pending(generated,[...existing,...occupied]);
 if(!rows.length){$('genError').textContent='Todos esses horários já estão cadastrados ou ocupados. Nenhum foi alterado.';return;}
 const {error}=await db.from('appointment_availability').insert(rows);if(error)throw error;
 saved=true;$('avError').textContent='';const notice=document.createElement('p');notice.className='av-success';notice.setAttribute('role','status');notice.textContent=rows.length+' horários criados. '+(generated.length-rows.length)+' existentes ou ocupados preservados.';document.querySelector('.av-success')?.remove();$('availabilityForm')?.after(notice);
 try{draw(await load());}catch{if($('avError'))$('avError').textContent='Horários salvos. Atualize a aba para conferir a lista.';}
 }catch(e){$('genError').textContent=e.code==='23505'?'Um horário foi cadastrado durante a geração. Tente novamente: os existentes serão preservados.':(e.message||'Não foi possível gerar os horários.');}
 finally{saving=false;if(saved)close();else{controls.forEach(el=>el.disabled=false);$('generatorSave').textContent='Gerar horários';}}
 };
 dialog.showModal();preview();
}
function setup(){if(!cfg.url||!cfg.anonKey||!window.supabase)return;db=window.supabase.createClient(cfg.url,cfg.anonKey);window.renderAvailability=render}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();