(()=>{'use strict';
const cfg=window.SUPABASE_CONFIG||{};
const $=id=>document.getElementById(id);
let db=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>{const [y,m,d]=String(v).split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).replace(/^./,c=>c.toUpperCase())};
async function load(){const rows=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('appointment_availability').select('id,available_date,available_time,active,professional').order('available_date',{ascending:true}).order('available_time',{ascending:true}).order('id',{ascending:true}).range(offset,offset+999);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)return rows;}}
let currentRows=[];
async function render(){
 const c=$('content');if(!c)return;
 c.innerHTML=`<div class="av-workspace"><section class="av-intro"><p class="eyebrow">AGENDA PÚBLICA</p><h1>Disponibilidade</h1><p>Controle quais dias e horários podem ser escolhidos pelas clientes.</p><div class="av-top-actions"><button id="openGenerator" type="button" class="action av-generate">Gerar horários</button><button id="avNewSlot" type="button" class="primary">＋ Novo horário</button></div></section><div id="avMetrics" class="av-metrics" aria-live="polite"></div><div class="card av-create-card" hidden>
 <div class="av-create"><section class="av-create__single"><h4>Adicionar um horário</h4><p>Cadastre uma vaga para uma ou para as duas profissionais.</p><form id="availabilityForm" class="av-single-fields"><label>Data<input id="avDate" type="date" required></label><label>Horário<input id="avTime" type="time" required></label><label class="av-full">Profissional<select id="avProfessional"><option value="both">Raquel e Iarytsa — vagas independentes</option><option value="raquel">Raquel</option><option value="iarytsa">Iarytsa</option></select></label><button class="primary" type="submit">Adicionar horário</button></form></section></div></div><p id="avError" class="error" role="alert"></p>
 <div class="card"><div class="card-head"><div><h3>Visualização da agenda</h3><p>Filtre os horários para encontrar rapidamente um dia.</p></div></div>
 <div class="av-quick-filters"><button type="button" class="action" data-av-period="all">Todos</button><button type="button" class="action" data-av-period="today">Hoje</button><button type="button" class="action" data-av-period="week">Próximos 7 dias</button></div><div class="av-filters"><label>Período<select id="avFilterPeriod"><option value="all">Todos os dias</option><option value="today">Hoje</option><option value="week">Próximos 7 dias</option><option value="upcoming">Hoje e próximos dias</option><option value="past">Histórico</option></select></label><label>Buscar uma data<input type="date" id="avFilterDate"></label><label>Profissional<select id="avFilterProfessional"><option value="all">Todas</option><option value="raquel">Raquel</option><option value="iarytsa">Iarytsa</option><option value="shared">Horários compartilhados</option></select></label><label>Status<select id="avFilterStatus"><option value="all">Todos</option><option value="active">Ativos</option><option value="blocked">Bloqueados</option></select></label></div>
 <div class="av-filter-tools"><span id="avFilterCount" class="av-filter-count" aria-live="polite"></span><button type="button" id="avClearFilters" class="action">Limpar filtros</button></div>
 <p class="av-list-note">Um horário ativo aparece para a cliente enquanto não estiver reservado. Horários compartilhados podem atender qualquer uma das profissionais.</p></div><div class="card av-agenda-card"><h3>Escolha um dia</h3><div id="availabilityList" class="av-days">Carregando horários...</div></div></div>`;
 if(!$('avMenuToggle')){const menu=document.createElement('button');menu.id='avMenuToggle';menu.type='button';menu.textContent='☰';menu.setAttribute('aria-label','Abrir menu administrativo');menu.setAttribute('aria-expanded','false');menu.onclick=()=>{const open=$('panel').classList.toggle('av-menu-open');menu.setAttribute('aria-expanded',String(open));};$('panel').querySelector('header').prepend(menu);$('panel').querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>{$('panel').classList.remove('av-menu-open');menu.setAttribute('aria-expanded','false');}));}
 $('avNewSlot').onclick=()=>{const card=c.querySelector('.av-create-card');card.hidden=!card.hidden;if(!card.hidden){card.scrollIntoView({behavior:'smooth',block:'start'});$('avDate').focus();}};
 c.querySelectorAll('[data-av-period]').forEach(button=>button.onclick=()=>{$('avFilterPeriod').value=button.dataset.avPeriod;$('avFilterPeriod').disabled=false;$('avFilterDate').value='';draw(currentRows);});
 $('availabilityForm').onsubmit=add;$('openGenerator').onclick=openGenerator;$('avDate').value=today();
 ['avFilterPeriod','avFilterDate','avFilterProfessional','avFilterStatus'].forEach(id=>$(id).onchange=()=>{if(id==='avFilterDate')$('avFilterPeriod').disabled=Boolean($('avFilterDate').value);draw(currentRows);});
 $('avClearFilters').onclick=()=>{$('avFilterPeriod').value='all';$('avFilterPeriod').disabled=false;$('avFilterDate').value='';$('avFilterProfessional').value='all';$('avFilterStatus').value='all';draw(currentRows);};
 try{draw(await load())}catch(e){$('availabilityList').innerHTML='<p class="error">'+esc(e.message)+'</p>'}
}
function draw(rows){
 const list=$('availabilityList');if(!list)return;currentRows=rows;
 const openDays=new Set([...list.querySelectorAll('details[open]')].map(el=>el.dataset.avDay));
 const filtered=window.AvailabilityView.filter(rows,{today:today(),date:$('avFilterDate').value,period:$('avFilterPeriod').value,professional:$('avFilterProfessional').value,status:$('avFilterStatus').value});
 const stats=window.AvailabilityView.summary(filtered);
 $('avFilterCount').textContent=filtered.length+' de '+rows.length+' horários cadastrados';
 $('avMetrics').innerHTML=[['Dias configurados',stats.days,'No filtro atual','days'],['Horários disponíveis',stats.active,'Ativos; reservas verificadas ao agendar','active'],['Bloqueados',stats.blocked,'Desativados manualmente','blocked'],['Horários cadastrados',filtered.length,'Total no filtro atual','total']].map(([label,count,note,state])=>'<div class="av-metric av-metric--'+state+'"><span>'+label+'</span><strong>'+count+'</strong><small>'+note+'</small></div>').join('');
 document.querySelectorAll('[data-av-period]').forEach(button=>{const selected=!$('avFilterDate').value&&button.dataset.avPeriod===$('avFilterPeriod').value;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});
 if(!filtered.length){list.innerHTML='<div class="av-empty">'+(rows.length?'Nenhum horário corresponde aos filtros. Tente outra data ou consulte o Histórico.':'Nenhum horário cadastrado. Use uma das opções acima para começar.')+'</div>';return;}
 list.innerHTML=window.AvailabilityView.group(filtered).map(([date,items],i)=>{
 const active=items.filter(row=>row.active).length;
 return '<details class="av-day" data-av-day="'+esc(date)+'" '+(openDays.has(date)||(!openDays.size&&i===0)?'open':'')+'><summary><span class="av-day__title">'+esc(fmtDate(date))+'<small>'+items.length+' horário(s) · '+active+' ativo(s) · '+(items.length-active)+' bloqueado(s)</small></span></summary><div class="av-day__body"><div class="av-day__tools"><p>Horários em ordem de atendimento</p><button class="action danger" type="button" data-block-date="'+esc(date)+'">Bloquear todo o dia</button></div><div class="av-slot-grid">'+items.map(row=>'<article class="av-slot '+(row.active?'':'av-slot--blocked')+'"><div class="av-slot__head"><strong class="av-slot__time">'+esc(String(row.available_time).slice(0,5))+'</strong><span class="av-slot__state">'+(row.active?'Ativo':'Bloqueado')+'</span></div><label>Profissional<select data-av-professional="'+esc(row.id)+'"><option value="" '+(!row.professional?'selected':'')+'>Compartilhado — Raquel ou Iarytsa</option><option value="raquel" '+(row.professional==='raquel'?'selected':'')+'>Raquel</option><option value="iarytsa" '+(row.professional==='iarytsa'?'selected':'')+'>Iarytsa</option></select></label><div class="av-slot__actions"><button class="action" type="button" data-toggle-av="'+esc(row.id)+'">'+(row.active?'Bloquear':'Ativar')+'</button><button class="action danger" type="button" data-delete-av="'+esc(row.id)+'">Excluir</button></div></article>').join('')+'</div></div></details>';
 }).join('');
 list.querySelectorAll('[data-av-professional]').forEach(el=>el.onchange=()=>changeProfessional(el));list.querySelectorAll('[data-toggle-av]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggleAv));list.querySelectorAll('[data-delete-av]').forEach(b=>b.onclick=()=>remove(b.dataset.deleteAv));list.querySelectorAll('[data-block-date]').forEach(b=>b.onclick=()=>blockDate(b.dataset.blockDate));
}
async function add(e){e.preventDefault();const button=e.submitter||$('availabilityForm').querySelector('button');button.disabled=true;$('avError').textContent='';try{const date=$('avDate').value,time=$('avTime').value;if(!date||!time)return;const rows=window.StudioProfessionals.expand($('avProfessional').value).map(professional=>({available_date:date,available_time:time+':00',active:true,professional}));const pending=window.AvailabilityGenerator.pending(rows,await load());if(!pending.length){$('avError').textContent='Esse horário já está cadastrado para a profissional escolhida.';return;}const {error}=await db.from('appointment_availability').insert(pending);if(error)throw error;draw(await load());}catch(e){$('avError').textContent=e.code==='23505'?'Esse horário já está cadastrado.':e.message;}finally{button.disabled=false;}}

async function changeProfessional(el){el.disabled=true;try{const rows=await load(),row=rows.find(r=>r.id===el.dataset.avProfessional);if(!row)return;const professional=el.value||null;if(rows.some(r=>r.id!==row.id&&r.available_date===row.available_date&&r.available_time===row.available_time&&window.StudioProfessionals.conflicts(r,{professional}))){el.value=row.professional||'';throw new Error('Já existe disponibilidade para essa profissional nesse horário.');}const {error}=await db.from('appointment_availability').update({professional,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)throw error;draw(await load());}catch(e){$('avError').textContent=e.message;try{draw(await load());}catch{}}finally{el.disabled=false;}}
async function toggle(id){const rows=await load(),r=rows.find(x=>x.id===id);if(!r)return;const {error}=await db.from('appointment_availability').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else draw(await load())}
async function remove(id){if(!confirm('Excluir este horário?'))return;const {error}=await db.from('appointment_availability').delete().eq('id',id);if(error)alert(error.message);else draw(await load())}
async function blockDate(date){if(!confirm('Bloquear TODOS os horários de '+fmtDate(date)+', incluindo os de outras profissionais ocultos pelos filtros?'))return;const {error}=await db.from('appointment_availability').update({active:false,updated_at:new Date().toISOString()}).eq('available_date',date);if(error)alert(error.message);else draw(await load())}

function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function openGenerator(){
 const dialog=document.createElement('dialog');dialog.className='av-generator';dialog.setAttribute('aria-labelledby','generatorTitle');
 dialog.innerHTML=`<form id="generatorForm"><div class="av-dialog-head"><div><h3 id="generatorTitle">Gerar horários de atendimento</h3><p>Crie vários horários para um dia ou repita a disponibilidade.</p></div><button type="button" class="action" id="generatorClose" aria-label="Fechar">✕</button></div>
 <label>Profissional<select id="genProfessional"><option value="both">Raquel e Iarytsa — vagas independentes</option><option value="raquel">Somente Raquel</option><option value="iarytsa">Somente Iarytsa</option></select></label><label>Dia inicial<input id="genDate" type="date" required></label>
 <div class="av-fields"><label>Horário inicial<input id="genStart" type="time" value="08:00" required></label><label>Fim do expediente<input id="genEnd" type="time" value="18:00" required></label><label>Intervalo entre horários<select id="genInterval"><option value="15">15 minutos</option><option value="20">20 minutos</option><option value="30" selected>30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="custom">Personalizado</option></select></label></div>
 <label id="genCustomField" hidden>Intervalo em minutos<input id="genCustom" type="number" min="1" max="720" step="1" value="30"></label>
 <p class="av-hint">São gerados inícios antes do fim do expediente. O intervalo não define a duração do serviço.</p>
 <div class="av-option-card"><label class="av-choice"><input id="genPause" type="checkbox"> Pausa para almoço / intervalo (opcional)</label><div class="av-fields" id="genPauseFields" hidden><label>Início da pausa<input id="genPauseStart" type="time" value="12:00"></label><label>Fim da pausa<input id="genPauseEnd" type="time" value="13:00"></label></div></div>
 <fieldset><legend>Aplicar em quais dias?</legend><label class="av-choice"><input type="radio" name="genMode" value="single" checked> Somente este dia</label><label class="av-choice"><input type="radio" name="genMode" value="repeat"> Repetir disponibilidade</label><div id="genRepeatFields" hidden><label>Repetir até<input id="genUntil" type="date"></label><div class="av-weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((name,i)=>`<label class="av-choice"><input type="checkbox" name="genWeekday" value="${i}" ${i>0&&i<6?'checked':''}>${name}</label>`).join('')}</div></div></fieldset>
 <div class="av-preview"><strong>Prévia dos horários</strong><p id="genSummary" aria-live="polite"></p><div id="genPreview" class="av-chips"></div><p class="av-hint">Horários existentes, bloqueados ou ocupados serão preservados e ignorados na geração.</p></div>
 <p id="genError" class="error" role="alert"></p><div class="av-dialog-actions"><button id="generatorCancel" type="button" class="action">Cancelar</button><button id="generatorSave" class="primary" type="submit">Gerar horários</button></div></form>`;
 document.body.append(dialog);$('genDate').value=$('avDate')?.value||today();$('genUntil').value=$('genDate').value;
 let saving=false;const close=()=>{if(saving)return;dialog.close();dialog.remove();$('openGenerator')?.focus();};
 $('generatorClose').onclick=close;$('generatorCancel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 const options=()=>({professional:$('genProfessional').value,date:$('genDate').value,start:$('genStart').value,end:$('genEnd').value,interval:$('genInterval').value==='custom'?$('genCustom').value:$('genInterval').value,pause:$('genPause').checked,pauseStart:$('genPauseStart').value,pauseEnd:$('genPauseEnd').value,repeat:dialog.querySelector('[name="genMode"]:checked').value==='repeat',until:$('genUntil').value,weekdays:[...dialog.querySelectorAll('[name="genWeekday"]:checked')].map(el=>Number(el.value))});
 const preview=()=>{if(saving)return;const o=options();$('genCustomField').hidden=$('genInterval').value!=='custom';$('genPauseFields').hidden=!o.pause;$('genRepeatFields').hidden=!o.repeat;$('genError').textContent='';try{const rows=window.AvailabilityGenerator.generate(o),times=[...new Set(rows.map(r=>r.available_time.slice(0,5)))],days=new Set(rows.map(r=>r.available_date)).size;$('genSummary').textContent=rows.length+' horários em '+days+' dia(s).';$('genPreview').innerHTML=times.map(t=>'<span>'+esc(t)+'</span>').join('');$('generatorSave').disabled=false;}catch(e){$('genError').textContent=e.message;$('genSummary').textContent='Revise a configuração.';$('genPreview').innerHTML='';$('generatorSave').disabled=true;}};
 $('generatorForm').addEventListener('input',preview);$('generatorForm').addEventListener('change',preview);
 $('generatorForm').onsubmit=async e=>{e.preventDefault();if(saving)return;let generated;try{generated=window.AvailabilityGenerator.generate(options());}catch(e){$('genError').textContent=e.message;return;}
 saving=true;const controls=[...dialog.querySelectorAll('input,select,button')];controls.forEach(el=>el.disabled=true);$('generatorSave').textContent='Gerando...';$('genError').textContent='';
 let saved=false;
 try{
 const existing=await load();const occupied=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('appointments').select('id,appointment_at,professional').in('status',['agendado','confirmado','concluido']).gte('appointment_at',generated[0].available_date+'T00:00:00-03:00').lte('appointment_at',generated[generated.length-1].available_date+'T23:59:59-03:00').order('id').range(offset,offset+999);if(error)throw error;for(const a of data||[]){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(a.appointment_at)).reduce((o,p)=>(o[p.type]=p.value,o),{});occupied.push({available_date:parts.year+'-'+parts.month+'-'+parts.day,available_time:parts.hour+':'+parts.minute,professional:a.professional});}if(!data||data.length<1000)break;}
 const rows=window.AvailabilityGenerator.pending(generated,[...existing,...occupied]);
 if(!rows.length){$('genError').textContent='Todos esses horários já estão cadastrados ou ocupados. Nenhum foi alterado.';return;}
 const {error}=await db.from('appointment_availability').insert(rows);if(error)throw error;
 saved=true;$('avError').textContent='';const notice=document.createElement('p');notice.className='av-success';notice.setAttribute('role','status');notice.textContent=rows.length+' horários criados. '+(generated.length-rows.length)+' existentes ou ocupados preservados.';document.querySelector('.av-success')?.remove();$('availabilityForm')?.after(notice);
 try{draw(await load());}catch{if($('avError'))$('avError').textContent='Horários salvos. Atualize a aba para conferir a lista.';}
 }catch(e){$('genError').textContent=e.code==='23505'?'Um horário foi cadastrado durante a geração. Tente novamente: os existentes serão preservados.':(e.message||'Não foi possível gerar os horários.');}
 finally{saving=false;if(saved)close();else{controls.forEach(el=>el.disabled=false);$('generatorSave').textContent='Gerar horários';}}
 };
 dialog.showModal();preview();
}
function setup(){if(!cfg.url||!cfg.anonKey||!window.supabase)return;db=window.supabase.createClient(cfg.url,cfg.anonKey);window.renderAvailability=render}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();