(()=>{'use strict';
const cfg=window.SUPABASE_CONFIG||{};if(!window.supabase||!cfg.url||!cfg.anonKey)return;
const db=window.supabase.createClient(cfg.url,cfg.anonKey),api=window.IRReviews;let rows=[],page=0,version=0;
const professional=p=>p==='raquel'?'Raquel':p==='iarytsa'?'Iarytsa':'Espaço I.R';
const date=value=>new Date(value).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'});
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
function draw(){const list=document.getElementById('reviewAdminList');if(!list)return;const status=document.getElementById('reviewStatusFilter').value,prof=document.getElementById('reviewProfessionalFilter').value;const filtered=rows.filter(r=>(prof==='all'||r.professional===prof)&&(status==='all'||(status==='received'?Boolean(r.rating):!r.rating)));
list.innerHTML=filtered.length?filtered.map(r=>'<article class="review-admin-card" data-review-record="'+api.esc(r.source+'|'+r.source_id)+'"><div class="review-admin-head"><div><strong>'+api.esc(r.client_name||'Cliente')+'</strong><p>'+api.esc(r.service_name||'Atendimento')+' · '+api.esc(professional(r.professional))+' · '+api.esc(date(r.service_date))+'</p></div><span class="review-state">'+(r.rating?'Recebida':'Aguardando avaliação')+'</span></div>'+(r.rating?'<p class="review-received-stars" aria-label="'+r.rating+' de 5 estrelas">'+api.stars(r.rating)+'</p><p class="review-feedback">'+api.esc(r.comment||'A cliente enviou somente a nota.')+'</p>':'<button type="button" class="action" data-review-generate>Gerar link de avaliação</button><div class="review-link-result" hidden><label>Link da cliente<input class="review-generated-link" type="text" readonly></label><div class="review-link-actions"><button type="button" class="action" data-review-copy>Copiar link</button><a class="action review-whatsapp" target="_blank" rel="noopener noreferrer" hidden>Preparar no WhatsApp</a></div></div><p class="review-record-message" role="status"></p>')+'</article>').join(''):'<p class="empty">Nenhum atendimento neste filtro. Os links ficam disponíveis após concluir o serviço.</p>';
list.querySelectorAll('[data-review-generate]').forEach(button=>button.onclick=async()=>{const card=button.closest('[data-review-record]'),key=card.dataset.reviewRecord,r=rows.find(row=>row.source+'|'+row.source_id===key),feedback=card.querySelector('.review-record-message');button.disabled=true;button.textContent='Gerando…';try{const token=await rpc('issue_service_review_link',{p_source:r.source,p_source_id:r.source_id}),link=api.linkFor(token);r.token=token;card.querySelector('.review-generated-link').value=link;card.querySelector('.review-link-result').hidden=false;button.hidden=true;feedback.textContent='Link pronto. Copie e envie para a cliente.';let phone=String(r.client_phone||'').replace(/\D/g,'');if(phone.length===10||phone.length===11)phone='55'+phone;if(/^55\d{10,11}$/.test(phone)){const whatsapp=card.querySelector('.review-whatsapp');whatsapp.href='https://wa.me/'+phone+'?text='+encodeURIComponent('Olá, '+r.client_name+'! Como foi seu atendimento no Espaço I.R? Avalie pelo link: '+link);whatsapp.hidden=false;}}catch(error){feedback.textContent=api.message(error);button.disabled=false;button.textContent='Gerar link de avaliação';}});
list.querySelectorAll('[data-review-copy]').forEach(button=>button.onclick=async()=>{const card=button.closest('[data-review-record]'),input=card.querySelector('.review-generated-link');try{await navigator.clipboard.writeText(input.value);card.querySelector('.review-record-message').textContent='Link copiado.';}catch{input.focus();input.select();card.querySelector('.review-record-message').textContent='Selecione o link e copie para enviar à cliente.';}});
}
async function load(more=false){const mine=version,button=document.getElementById('reviewLoadMore'),errorBox=document.getElementById('reviewAdminError');if(!button)return;button.disabled=true;errorBox.textContent='';try{const data=await rpc('list_service_review_records',{p_offset:more?page*100:0});if(mine!==version||!document.getElementById('reviewAdminList'))return;const fetched=Array.isArray(data)?data:[];if(more){const seen=new Set(rows.map(r=>r.source+'|'+r.source_id));rows.push(...fetched.filter(r=>!seen.has(r.source+'|'+r.source_id)));}else rows=fetched;page=more?page+1:1;draw();button.hidden=fetched.length<100;}catch(error){if(mine===version){errorBox.textContent=api.message(error);const list=document.getElementById('reviewAdminList');if(list&&!rows.length)list.textContent='Não foi possível carregar as avaliações. Tente Atualizar.';}}finally{button.disabled=false;}}
function render(){version++;rows=[];page=0;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.reviewNav==='true'));document.getElementById('title').textContent='Avaliações';document.getElementById('content').innerHTML='<div class="card"><div class="card-head"><div><h3>Avaliações das clientes</h3><p>Gere o link após concluir o serviço e acompanhe as respostas.</p></div><button id="reviewAdminRefresh" class="action" type="button">Atualizar</button></div><div class="review-admin-filters"><label>Profissional<select id="reviewProfessionalFilter"><option value="all">Todas</option><option value="raquel">Raquel</option><option value="iarytsa">Iarytsa</option></select></label><label>Avaliações<select id="reviewStatusFilter"><option value="all">Todos os atendimentos</option><option value="received">Recebidas</option><option value="pending">Ainda não avaliados</option></select></label></div><p id="reviewAdminError" class="error" role="alert"></p><div id="reviewAdminList" class="review-admin-list">Carregando…</div><button id="reviewLoadMore" class="action" type="button" hidden>Carregar mais atendimentos</button></div>';document.getElementById('reviewProfessionalFilter').onchange=draw;document.getElementById('reviewStatusFilter').onchange=draw;document.getElementById('reviewAdminRefresh').onclick=()=>load();document.getElementById('reviewLoadMore').onclick=()=>load(true);load();}
function install(){const aside=document.getElementById('irAdminNavigation');if(!aside||aside.querySelector('[data-review-nav]'))return;const b=document.createElement('button');b.type='button';b.className='nav';b.dataset.reviewNav='true';b.title='Avaliações';b.innerHTML='<svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"></path></svg><span>Avaliações</span>';aside.querySelector('#logout')?.before(b);b.onclick=render;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
